# Generated by Django 5.1.4 on 2025-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата в рублях')),
            ],
            options={
                'verbose_name': 'Статистика зарплат',
                'verbose_name_plural': 'Статистика зарплат',
            },
        ),
        migrations.DeleteModel(
            name='CSVData',
        ),
    ]
